using System.ComponentModel.DataAnnotations; // Provides validation attributes like [Key]
using System.ComponentModel.DataAnnotations.Schema; // Allows configuration of database schema behavior
using System.Text.Json.Serialization; // Used to control JSON serialization behavior
using Hotdesk.Models; // References related models (e.g., Booking)

namespace Hotdesk.Components.Models
{
    // Represents a desk entity in the hotdesk booking system
    public class Desk
    {
        [Key] // Marks DeskId as the primary key in the database
        [DatabaseGenerated(DatabaseGeneratedOption.None)] // DeskId is manually assigned, not auto-generated by the database
        public int DeskId { get; set; }

        public string Name { get; set; } = string.Empty; // Name of the desk (e.g., "Desk A1")

        public string Location { get; set; } = string.Empty; // Physical location of the desk (e.g., "2nd Floor, Room 3")

        public bool HasMonitor { get; set; } // Indicates if the desk comes with a monitor

        public bool IsAvailable { get; set; } = true; // Tracks whether the desk is available for booking (default: true)

        public string? Description { get; set; } // Optional field for additional information about the desk

        [JsonIgnore] // Prevents this property from being included in JSON responses (avoids circular reference issues)
        public virtual ICollection<Booking>? Bookings { get; set; } // Navigation property linking desk to related bookings
    }
}

